In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=pd.read_csv("/content/Ind_Exp_Nifty_merged.csv"); data

Unnamed: 0        Date      Open      High       Low     Close  \
0              0  2022-05-06  34569.10  34797.95  34353.20  34591.20   
1              1  2022-05-05  35705.35  35934.85  35133.80  35232.85   
2              2  2022-05-04  36266.15  36309.30  35127.85  35264.55   
3              3  2022-05-02  35627.60  36235.25  35618.20  36163.75   
4              4  2022-04-29  36474.05  36718.80  35978.95  36088.15   
...          ...         ...       ...       ...       ...       ...   
3299        3299  2009-01-07   5416.35   5440.55   4954.00   4984.50   
3300        3300  2009-01-06   5333.50   5448.80   5276.40   5395.30   
3301        3301  2009-01-05   5273.45   5371.10   5273.45   5359.40   
3302        3302  2009-01-02   5154.20   5258.65   5103.60   5195.10   
3303        3303  2009-01-01   5019.20   5135.15   5019.20   5116.50   

                                              Headlines  \
0                                                   NaN   
1            ‘Rate cycle U-turn: RBI may go for more’.    
2     RBI raises CRR by 50 bps to 4.5% from May 21. ...   
3     Bank holidays in May 2022: Here is the list of...   
4     To plug support package loopholes, Nabard plan...   
...                                                 ...   
3299                                                NaN   
3300                                                NaN   
3301                                                NaN   
3302                                                NaN   
3303                                                NaN   

                                       Sentiment  
0                                            NaN  
1       [0.9999913, 1.1432373e-06, 7.482723e-06]  
2     [0.99954671, 0.00041552441, 3.7765163e-05]  
3     [0.99998772, 6.8683225e-06, 5.3801709e-06]  
4     [0.99999213, 5.6305475e-07, 7.2760436e-06]  
...                                          ...  
3299                                         NaN  
3300                                         NaN  
3301                                         NaN  
3302                                         NaN  
3303                                         NaN  

[3304 rows x 8 columns]

In [ ]:
data=data.drop(data.columns[0],axis=1);data

Date      Open      High       Low     Close  \
0     2022-05-06  34569.10  34797.95  34353.20  34591.20   
1     2022-05-05  35705.35  35934.85  35133.80  35232.85   
2     2022-05-04  36266.15  36309.30  35127.85  35264.55   
3     2022-05-02  35627.60  36235.25  35618.20  36163.75   
4     2022-04-29  36474.05  36718.80  35978.95  36088.15   
...          ...       ...       ...       ...       ...   
3299  2009-01-07   5416.35   5440.55   4954.00   4984.50   
3300  2009-01-06   5333.50   5448.80   5276.40   5395.30   
3301  2009-01-05   5273.45   5371.10   5273.45   5359.40   
3302  2009-01-02   5154.20   5258.65   5103.60   5195.10   
3303  2009-01-01   5019.20   5135.15   5019.20   5116.50   

                                              Headlines  \
0                                                   NaN   
1            ‘Rate cycle U-turn: RBI may go for more’.    
2     RBI raises CRR by 50 bps to 4.5% from May 21. ...   
3     Bank holidays in May 2022: Here is the list of...   
4     To plug support package loopholes, Nabard plan...   
...                                                 ...   
3299                                                NaN   
3300                                                NaN   
3301                                                NaN   
3302                                                NaN   
3303                                                NaN   

                                       Sentiment  
0                                            NaN  
1       [0.9999913, 1.1432373e-06, 7.482723e-06]  
2     [0.99954671, 0.00041552441, 3.7765163e-05]  
3     [0.99998772, 6.8683225e-06, 5.3801709e-06]  
4     [0.99999213, 5.6305475e-07, 7.2760436e-06]  
...                                          ...  
3299                                         NaN  
3300                                         NaN  
3301                                         NaN  
3302                                         NaN  
3303                                         NaN  

[3304 rows x 7 columns]

In [ ]:
S=data['Sentiment'];S

0                                              NaN
1         [0.9999913, 1.1432373e-06, 7.482723e-06]
2       [0.99954671, 0.00041552441, 3.7765163e-05]
3       [0.99998772, 6.8683225e-06, 5.3801709e-06]
4       [0.99999213, 5.6305475e-07, 7.2760436e-06]
                           ...                    
3299                                           NaN
3300                                           NaN
3301                                           NaN
3302                                           NaN
3303                                           NaN
Name: Sentiment, Length: 3304, dtype: object

In [ ]:
S[1]

'[0.9999913, 1.1432373e-06, 7.482723e-06]'

In [ ]:
for  j in range(len(S)):
  if S.isna()[j]==False:
    s=S[j].replace('[','').replace(',','').replace(']','').split()
    for i in range(len(s)):
      s[i]=float(s[i])
    S[j]=s


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
for j in range(len(S)):
  if S.isna()[j]==False:
    s=np.array(S[j])
    S[j]=s

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


In [ ]:
for j in range(len(S)):
  if S.isna()[j]==True:
    S[j]=np.NaN

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
np.mean(S[0:7])

array([9.98220980e-01, 1.76668126e-03, 1.23147655e-05])

In [ ]:
S.isna()[0]

True

In [ ]:
df=S[0:7]; df

0                                           NaN
1      [0.9999913, 1.1432373e-06, 7.482723e-06]
2    [0.99954671, 0.00041552441, 3.7765163e-05]
3    [0.99998772, 6.8683225e-06, 5.3801709e-06]
4    [0.99999213, 5.6305475e-07, 7.2760436e-06]
5     [0.99158704, 0.0084093073, 3.6697272e-06]
6                                           NaN
Name: Sentiment, dtype: object

In [ ]:
df=[np.mean(df) if i is np.NaN else i for i in df]; df

[array([9.98220980e-01, 1.76668126e-03, 1.23147655e-05]),
 array([9.9999130e-01, 1.1432373e-06, 7.4827230e-06]),
 array([9.9954671e-01, 4.1552441e-04, 3.7765163e-05]),
 array([9.9998772e-01, 6.8683225e-06, 5.3801709e-06]),
 array([9.9999213e-01, 5.6305475e-07, 7.2760436e-06]),
 array([9.9158704e-01, 8.4093073e-03, 3.6697272e-06]),
 array([9.98220980e-01, 1.76668126e-03, 1.23147655e-05])]

In [ ]:
S[0:7]=df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
S[range(7,len(S))]

7                                              NaN
8          [0.11481908, 0.88515502, 2.5873765e-05]
9             [0.01240634, 0.98567075, 0.00192289]
10      [0.99998987, 2.6581588e-06, 7.4588661e-06]
11      [0.99999535, 2.3880739e-06, 2.2547556e-06]
                           ...                    
3299                                           NaN
3300                                           NaN
3301                                           NaN
3302                                           NaN
3303                                           NaN
Name: Sentiment, Length: 3297, dtype: object

In [ ]:
for i in range(7,len(S)):
  if S.isna()[i]==True:
    S[i]=np.mean(S[i-7:i-1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
S

0       [0.9982209799999999, 0.00176668126491, 1.23147...
1                [0.9999913, 1.1432373e-06, 7.482723e-06]
2              [0.99954671, 0.00041552441, 3.7765163e-05]
3              [0.99998772, 6.8683225e-06, 5.3801709e-06]
4              [0.99999213, 5.6305475e-07, 7.2760436e-06]
                              ...                        
3299    [0.9662993119282969, 0.0011795088525012685, 0....
3300    [0.9662992800837604, 0.0011795088624957054, 0....
3301    [0.9662994447176895, 0.0011795025161276122, 0....
3302    [0.966299540037182, 0.0011794998255569799, 0.0...
3303    [0.9662995791893328, 0.0011794987979897708, 0....
Name: Sentiment, Length: 3304, dtype: object

In [ ]:
data['Sentiment']=S

In [ ]:
data

Date      Open      High       Low     Close  \
0     2022-05-06  34569.10  34797.95  34353.20  34591.20   
1     2022-05-05  35705.35  35934.85  35133.80  35232.85   
2     2022-05-04  36266.15  36309.30  35127.85  35264.55   
3     2022-05-02  35627.60  36235.25  35618.20  36163.75   
4     2022-04-29  36474.05  36718.80  35978.95  36088.15   
...          ...       ...       ...       ...       ...   
3299  2009-01-07   5416.35   5440.55   4954.00   4984.50   
3300  2009-01-06   5333.50   5448.80   5276.40   5395.30   
3301  2009-01-05   5273.45   5371.10   5273.45   5359.40   
3302  2009-01-02   5154.20   5258.65   5103.60   5195.10   
3303  2009-01-01   5019.20   5135.15   5019.20   5116.50   

                                              Headlines  \
0                                                   NaN   
1            ‘Rate cycle U-turn: RBI may go for more’.    
2     RBI raises CRR by 50 bps to 4.5% from May 21. ...   
3     Bank holidays in May 2022: Here is the list of...   
4     To plug support package loopholes, Nabard plan...   
...                                                 ...   
3299                                                NaN   
3300                                                NaN   
3301                                                NaN   
3302                                                NaN   
3303                                                NaN   

                                              Sentiment  
0     [0.9982209799999999, 0.00176668126491, 1.23147...  
1              [0.9999913, 1.1432373e-06, 7.482723e-06]  
2            [0.99954671, 0.00041552441, 3.7765163e-05]  
3            [0.99998772, 6.8683225e-06, 5.3801709e-06]  
4            [0.99999213, 5.6305475e-07, 7.2760436e-06]  
...                                                 ...  
3299  [0.9662993119282969, 0.0011795088525012685, 0....  
3300  [0.9662992800837604, 0.0011795088624957054, 0....  
3301  [0.9662994447176895, 0.0011795025161276122, 0....  
3302  [0.966299540037182, 0.0011794998255569799, 0.0...  
3303  [0.9662995791893328, 0.0011794987979897708, 0....  

[3304 rows x 7 columns]

In [ ]:
data.to_csv('/content/handled_NaN.csv', index=False)